project:
  type: website

website:
  title: "Posit SDK"
  navbar:
    left:
      - text: Installation
        file: installation.qmd
      - text: Quick Start
        file: quickstart.qmd
      - text: Reference
        file: reference/index.qmd

filters:
  - interlinks

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

interlinks:
  sources:
    python:
      url: https://docs.python.org/3/
    requests:
      url: https://requests.readthedocs.io/en/latest/

quartodoc:
  title: API Reference
  style: pkgdown
  dir: reference
  package: posit
  render_interlinks: true
  options:
      include_attributes: true
      include_classes: true
      include_functions: true
      include_empty: true
  sections:
    - title: Clients
      package: posit
      desc: >
        The `Client` is the entrypoint for each Posit product. Initialize a `Client` to get started.
      contents:
        - name: connect.Client
          members:
            - content
            - metrics
            - tasks
            - users
            - request
            - get
            - post
            - put
            - patch
            - delete
    - title: Posit Connect
      package: posit
      contents:
        - connect.bundles
        - connect.content
        - connect.metrics.Metrics
        - connect.permissions
        - connect.tasks
        - connect.users
