name: Coverage Report
on:
  workflow_run:
    workflows: ["Coverage"]
    types:
      - completed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  actions: read
  contents: read
  pull-requests: write
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: coverage.xml
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: techman83/coverage@6aed45bb96bc879e66b35f0d88f6cf9adf01334c
        with:
            coverageFile: coverage.xml
            token: ${{ secrets.GITHUB_TOKEN }}
