name: Coverage
on:
  - pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  cov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup UV
        uses: astral-sh/setup-uv@v3

      - name: Install UV Python
        run: uv python install

      - name: Setup development environment
        run: make dev

      - name: Run tests
        run: make test

      - name: Generate coverage report
        run: make cov-xml

      - name: Upload coverage report
        if: ${{ ! github.event.pull_request.head.repo.fork }}
        uses: orgoro/coverage@v3.2
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
