name: Documentation
on:
  - pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
          check-latest: true
          cache: 'pip'
      - uses: quarto-dev/quarto-actions/setup@v2
      - run: make deps
      - run: make dev
      - run: make docs
      - uses: actions/setup-node@v4
      - run: npx -y netlify-cli deploy --dir docs/_site
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: 5cea1f56-7935-4387-975a-18a7905d15ee
