name: Release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  default:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - run: make
    - id: release
      uses: pypa/gh-action-pypi-publish@release/v1
