name: Release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  default:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - uses: actions/setup-node@v4
    - run: make deps
    - run: make build
    - run: make install
    - run: make docs
    - id: release
      uses: pypa/gh-action-pypi-publish@release/v1
    - id: site
      working-directory: docs
      env:
        ENV: prod
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      run: make deploy
