name: Release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  default:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup UV
        uses: astral-sh/setup-uv@v3

      - name: Install UV Python
        run: uv python install

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Build project
        run: make build

      - name: Install project
        run: make install

      - name: Publish to PyPI
        id: release
        uses: pypa/gh-action-pypi-publish@release/v1
